[tool.poetry]
name = "scid-bot-3"
version = "0.1.0"
description = ""
authors = ["Kseniya Tetercheva <snegurka.tkd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.13.1"
pydantic = "^2.9.2"
python-dotenv = "^1.0.1"
alembic = "^1.13.2"
sqlalchemy = "^2.0.35"
psycopg2-binary = "^2.9.9"
pydantic-settings = "^2.5.2"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
